In [1]:
import polars as pl

## Loading and Inspecting Data

### Main Dataframe (here Finland only)
Demonstrates use of:
- col
- read_parquet
- select
- filter
- schema
- head
- describe
- height
- width
- shape

In [2]:
columns_of_interest = [
    pl.col("entity_content"),
    pl.col("entity_category"),
    pl.col("sentence_content_current"),
    pl.col("sentence_content_previous"),
    pl.col("sentence_content_next"),
    pl.col("country"),
    pl.col("entity_word_id"),
    pl.col("session_date"),
    pl.col("speaker_id"),
    pl.col("speaker_ana"),
    pl.col("sentence_sentiment_value"),
    pl.col("debate_topic")
]

In [3]:
df = pl.read_parquet("../data/facts/FIN*.parquet").select(
    columns_of_interest
).filter(
    pl.col("speaker_ana") == "regular"
)
df.schema

Schema([('entity_content', String),
        ('entity_category', String),
        ('sentence_content_current', String),
        ('sentence_content_previous', String),
        ('sentence_content_next', String),
        ('country', String),
        ('entity_word_id', String),
        ('session_date', Date),
        ('speaker_id', String),
        ('speaker_ana', String),
        ('sentence_sentiment_value', Float32),
        ('debate_topic', String)])

In [4]:
df.head()

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ entity_co ┆ entity_ca ┆ sentence_ ┆ sentence_ ┆ … ┆ speaker_i ┆ speaker_a ┆ sentence_ ┆ debate_t │
│ ntent     ┆ tegory    ┆ content_c ┆ content_p ┆   ┆ d         ┆ na        ┆ sentiment ┆ opic     │
│ ---       ┆ ---       ┆ urrent    ┆ revious   ┆   ┆ ---       ┆ ---       ┆ _value    ┆ ---      │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆ f32       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Small Par ┆ LOC       ┆ Members   ┆ Mr        ┆ … ┆ SirkkaLii ┆ regular   ┆ 2.456     ┆ other    │
│ liament   ┆           ┆ of the    ┆ President ┆   ┆ saAnttila ┆           ┆           ┆          │
│           ┆           ┆ large com ┆ !         ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ mittee…   ┆           ┆   ┆           ┆           ┆           ┆          │
│ Constitut ┆ ORG       ┆ The       ┆ Mr.       ┆ … ┆ PerttiSal ┆ regular   ┆ 2.39      ┆ other    │
│ ional     ┆           ┆ members   ┆ Speaker ! ┆   ┆ olainen   ┆           ┆           ┆          │
│ Committee ┆           ┆ of the    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Constitut ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ io…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ Committee ┆ ORG       ┆ The       ┆ Mr.       ┆ … ┆ SeppoKäär ┆ regular   ┆ 2.426     ┆ mixed    │
│ on        ┆           ┆ members   ┆ Speaker ! ┆   ┆ iäinen    ┆           ┆           ┆          │
│ Foreign   ┆           ┆ of the    ┆           ┆   ┆           ┆           ┆           ┆          │
│ Affairs   ┆           ┆ Committee ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ o…        ┆           ┆   ┆           ┆           ┆           ┆          │
│ Committee ┆ ORG       ┆ The       ┆ Mr.       ┆ … ┆ SeppoKäär ┆ regular   ┆ 2.426     ┆ mixed    │
│           ┆           ┆ members   ┆ Speaker ! ┆   ┆ iäinen    ┆           ┆           ┆          │
│           ┆           ┆ of the    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Committee ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ o…        ┆           ┆   ┆           ┆           ┆           ┆          │
│ Small Par ┆ ORG       ┆ The       ┆ Mr.       ┆ … ┆ SeppoKäär ┆ regular   ┆ 2.426     ┆ mixed    │
│ liament   ┆           ┆ members   ┆ Speaker ! ┆   ┆ iäinen    ┆           ┆           ┆          │
│           ┆           ┆ of the    ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Committee ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ o…        ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [5]:
df.describe()

shape: (9, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ entity_co ┆ entity_ca ┆ sentence_ ┆ … ┆ speaker_i ┆ speaker_a ┆ sentence_ ┆ debate_t │
│ ---       ┆ ntent     ┆ tegory    ┆ content_c ┆   ┆ d         ┆ na        ┆ sentiment ┆ opic     │
│ str       ┆ ---       ┆ ---       ┆ urrent    ┆   ┆ ---       ┆ ---       ┆ _value    ┆ ---      │
│           ┆ str       ┆ str       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆ str       ┆   ┆           ┆           ┆ f64       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 39210     ┆ 39210     ┆ 39210     ┆ … ┆ 39210     ┆ 39210     ┆ 39210.0   ┆ 39210    │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.181256  ┆ null     │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 1.62246   ┆ null     │
│ min       ┆ -American ┆ LOC       ┆ " Abbrevi ┆ … ┆ AilaPalon ┆ regular   ┆ -0.146    ┆ argic    │
│           ┆           ┆           ┆ ation of  ┆   ┆ iemi      ┆           ┆           ┆          │
│           ┆           ┆           ┆ the time  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ lim…      ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.49      ┆ null     │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 2.297     ┆ null     │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ 3.462     ┆ null     │
│ max       ┆ ärade     ┆ PER       ┆ — When Mr ┆ … ┆ WilleRydm ┆ regular   ┆ 5.739     ┆ welfa    │
│           ┆           ┆           ┆ Terho     ┆   ┆ an        ┆           ┆           ┆          │
│           ┆           ┆           ┆ spoke of  ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ the f…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
print(f"{df.height} rows, {df.width} columns – shape: {df.shape}")

39210 rows, 12 columns – shape: (39210, 12)

### Joined Metadata Frame
Demonstrates use of:
- join
- filter
- exclude
- select

In [7]:
df_meta = pl.read_parquet("../data/Master_People.parquet"
                          ).join(
    pl.read_parquet("../data/Master_Affiliations.parquet").filter(
        (pl.col("start_date") < "2016") # note that the dates here are str (due to different formats present)
        & (pl.col("start_date") > "2014")
    ),
    on=["speaker_id","country"],
    how="inner"
).join(
    pl.read_parquet("../data/Master_Organizations.parquet").select(
        pl.exclude(["country"])
    ),
    on="org_id",
    how="inner"
).filter(
    [
        (pl.col("country") == "FIN")
    ]
)
df_meta.schema

Schema([('country', String),
        ('speaker_id', String),
        ('speaker_name', String),
        ('speaker_birth_year', String),
        ('speaker_gender', String),
        ('speaker_place_of_birth', String),
        ('org_id', String),
        ('role', String),
        ('start_date', String),
        ('end_date', String),
        ('org_name', String),
        ('org_role', String),
        ('party_ches_id', String),
        ('party_left_right_orientation', String)])

In [8]:
df_meta.head()

shape: (5, 14)
┌─────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ country ┆ speaker_id ┆ speaker_n ┆ speaker_b ┆ … ┆ org_name  ┆ org_role  ┆ party_che ┆ party_lef │
│ ---     ┆ ---        ┆ ame       ┆ irth_year ┆   ┆ ---       ┆ ---       ┆ s_id      ┆ t_right_o │
│ str     ┆ str        ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ rientatio │
│         ┆            ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆ n         │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---       │
│         ┆            ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞═════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ FIN     ┆ MarkusMust ┆ Mustajärv ┆ 1963      ┆ … ┆ Suomen    ┆ parliamen ┆ null      ┆ null      │
│         ┆ ajärvi     ┆ i Markus  ┆           ┆   ┆ eduskunta ┆ t         ┆           ┆           │
│ FIN     ┆ MarkusMust ┆ Mustajärv ┆ 1963      ┆ … ┆ Vasemmist ┆ political ┆ 1404      ┆ orientati │
│         ┆ ajärvi     ┆ i Markus  ┆           ┆   ┆ oliitto   ┆ Party     ┆           ┆ on.L      │
│ FIN     ┆ SamiSavio  ┆ Savio     ┆ 1975      ┆ … ┆ Suomen    ┆ parliamen ┆ null      ┆ null      │
│         ┆            ┆ Sami      ┆           ┆   ┆ eduskunta ┆ t         ┆           ┆           │
│ FIN     ┆ SamiSavio  ┆ Savio     ┆ 1975      ┆ … ┆ Pozitivna ┆ parliamen ┆ 2914      ┆ orientati │
│         ┆            ┆ Sami      ┆           ┆   ┆ Slovenija ┆ taryGroup ┆           ┆ on.CCL    │
│ FIN     ┆ SamiSavio  ┆ Savio     ┆ 1975      ┆ … ┆ Perussuom ┆ political ┆ 1405      ┆ orientati │
│         ┆            ┆ Sami      ┆           ┆   ┆ alaiset   ┆ Party     ┆           ┆ on.RRF    │
└─────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
df_meta.describe()

shape: (9, 15)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ statistic  ┆ country ┆ speaker_i ┆ speaker_n ┆ … ┆ org_name  ┆ org_role  ┆ party_che ┆ party_lef │
│ ---        ┆ ---     ┆ d         ┆ ame       ┆   ┆ ---       ┆ ---       ┆ s_id      ┆ t_right_o │
│ str        ┆ str     ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ rientatio │
│            ┆         ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆ n         │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ ---       │
│            ┆         ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ count      ┆ 936     ┆ 936       ┆ 936       ┆ … ┆ 936       ┆ 936       ┆ 108       ┆ 133       │
│ null_count ┆ 0       ┆ 0         ┆ 0         ┆ … ┆ 0         ┆ 0         ┆ 828       ┆ 803       │
│ mean       ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ std        ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ min        ┆ FIN     ┆ Alexander ┆ Aalto     ┆ … ┆ Bundesreg ┆ governmen ┆ 1401      ┆ orientati │
│            ┆         ┆ Stubb     ┆ Touko     ┆   ┆ ierung    ┆ t         ┆           ┆ on.C      │
│            ┆         ┆           ┆           ┆   ┆ der       ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ Republik  ┆           ┆           ┆           │
│            ┆         ┆           ┆           ┆   ┆ Ö…        ┆           ┆           ┆           │
│ 25%        ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 50%        ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 75%        ┆ null    ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ max        ┆ FIN     ┆ Ympäristö ┆ Yanar     ┆ … ┆ Κυβέρνηση ┆ political ┆ 3102      ┆ orientati │
│            ┆         ┆ jailmasto ┆ Ozan      ┆   ┆ της       ┆ Party     ┆           ┆ on.RRF    │
│            ┆         ┆ ministeri ┆           ┆   ┆ Ελληνικής ┆           ┆           ┆           │
│            ┆         ┆ Kri…      ┆           ┆   ┆ Δημοκρ…   ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Munging Data
Demonstrates:
- group_by
- agg
- len
- sort
- alias
- eval
- starts_with
- mean
- element
- value_counts
- get_column
- item
- strip_chars
- contains

Plus namespace functions:
- str
- list
- struct

In [10]:
df.group_by([pl.col("entity_category"), pl.col("entity_content")]).agg(
    pl.len()
).sort("len", descending=True)

shape: (5_324, 3)
┌─────────────────┬─────────────────────────────────┬──────┐
│ entity_category ┆ entity_content                  ┆ len  │
│ ---             ┆ ---                             ┆ ---  │
│ str             ┆ str                             ┆ u32  │
╞═════════════════╪═════════════════════════════════╪══════╡
│ LOC             ┆ Finland                         ┆ 5119 │
│ MISC            ┆ EUR                             ┆ 2190 │
│ MISC            ┆ Finnish                         ┆ 1869 │
│ MISC            ┆ Finns                           ┆ 742  │
│ ORG             ┆ Government Programme            ┆ 654  │
│ …               ┆ …                               ┆ …    │
│ LOC             ┆ Utsjoki Nuorgam                 ┆ 1    │
│ ORG             ┆ Minister for the Environment a… ┆ 1    │
│ LOC             ┆ Raahe                           ┆ 1    │
│ PER             ┆ Aha                             ┆ 1    │
│ PER             ┆ Cameron                         ┆ 1    │
└─────────────────┴─────────────────────────────────┴──────┘

In [11]:
df.filter(
    pl.col("entity_content").str.starts_with("Swe")
).group_by(
    ["entity_content", "entity_category"],
    maintain_order=True
).agg(
    pl.len().alias("count"),
    pl.col("sentence_sentiment_value").mean().alias("mean_sentiment"),
    pl.col("debate_topic")
).with_columns(
    pl.col("debate_topic").list.sort().list.eval(pl.element().value_counts()
                                                 ).list.eval(
        pl.element().sort_by(pl.element().struct.field("count"), descending=True)
    ).alias("debate_topic_records")
)

shape: (6, 6)
┌────────────────────┬─────────────────┬───────┬────────────────┬──────────────┬───────────────────┐
│ entity_content     ┆ entity_category ┆ count ┆ mean_sentiment ┆ debate_topic ┆ debate_topic_reco │
│ ---                ┆ ---             ┆ ---   ┆ ---            ┆ ---          ┆ rds               │
│ str                ┆ str             ┆ u32   ┆ f32            ┆ list[str]    ┆ ---               │
│                    ┆                 ┆       ┆                ┆              ┆ list[struct[2]]   │
╞════════════════════╪═════════════════╪═══════╪════════════════╪══════════════╪═══════════════════╡
│ Sweden             ┆ LOC             ┆ 393   ┆ 2.133595       ┆ ["immig",    ┆ [{"macro",66},    │
│                    ┆                 ┆       ┆                ┆ "inter", …   ┆ {"inter",53}, ……  │
│                    ┆                 ┆       ┆                ┆ "housi"]     ┆                   │
│ Swedish            ┆ MISC            ┆ 123   ┆ 2.222715       ┆ ["defen",    ┆ [{"educa",28},    │
│                    ┆                 ┆       ┆                ┆ "macro", …   ┆ {"immig",16}, ……  │
│                    ┆                 ┆       ┆                ┆ "envir"]     ┆                   │
│ Swedes             ┆ MISC            ┆ 6     ┆ 2.658667       ┆ ["macro",    ┆ [{"envir",2},     │
│                    ┆                 ┆       ┆                ┆ "envir", …   ┆ {"macro",1}, … {… │
│                    ┆                 ┆       ┆                ┆ "domes"]     ┆                   │
│ Swedish People 's  ┆ ORG             ┆ 2     ┆ 4.323          ┆ ["mixed",    ┆ [{"welfa",1},     │
│ Party              ┆                 ┆       ┆                ┆ "welfa"]     ┆ {"mixed",1}]      │
│ Swedish            ┆ ORG             ┆ 3     ┆ 3.463333       ┆ ["mixed",    ┆ [{"macro",1},     │
│ Parliamentary      ┆                 ┆       ┆                ┆ "macro",     ┆ {"labor",1}, {"m… │
│ Group              ┆                 ┆       ┆                ┆ "labor"]     ┆                   │
│ Swedish National   ┆ ORG             ┆ 2     ┆ 0.5365         ┆ ["healt",    ┆ [{"civil",1},     │
│ Audit Office       ┆                 ┆       ┆                ┆ "civil"]     ┆ {"healt",1}]      │
└────────────────────┴─────────────────┴───────┴────────────────┴──────────────┴───────────────────┘

In [12]:
df.get_column("sentence_content_current")

shape: (39_210,)
Series: 'sentence_content_current' [str]
[
	"Members of the large committee…
	"The members of the Constitutio…
	"The members of the Committee o…
	"The members of the Committee o…
	"The members of the Committee o…
	…
	"It is up to us to decide wheth…
	"To be more precise , I intende…
	"In paragraph 7 , I was meant t…
	"In paragraph 7 , I was meant t…
	"By way of derogation from my m…
]

In [13]:
df.filter(
    (pl.col("entity_category") == "LOC")
    &
    (pl.col("entity_content").str.contains(r"[Rr]ussia")) # Regex is supported
).select(
    # We're creating a new column from several existing columns
    (
            pl.col("sentence_content_previous").fill_null("")
            + " "
            + pl.col("sentence_content_current")
            + " "
            + pl.col("sentence_content_next").fill_null("")
    ).str.strip_chars().alias("sentence_with_context")
).item(10,"sentence_with_context")

"It is real and , as I said , in practice we do not know what the actual number of recruits is and what their activity is . Nor has the crisis between Russia and Ukraine subsided , but the unrest , as well as Russia 's certain isolation , are obvious all the time and , as the President - in - Office mentioned , Russia is not taking part in the Council of Europe 's activities as before , there is no similar negotiating link . We are also talking about a change in the security environment ."

In [14]:
df.get_column("entity_content")

shape: (39_210,)
Series: 'entity_content' [str]
[
	"Small Parliament"
	"Constitutional Committee"
	"Committee on Foreign Affairs"
	"Committee"
	"Small Parliament"
	…
	"Finland"
	"Section 35"
	"Metsähallitus"
	"Sami"
	"Ministry of the Environment"
]